export enum SellingPlanPricingPolicyAdjustmentType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  PRICE = 'PRICE',
}
export enum CurrencyCode {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  CAD = 'CAD',
  AFN = 'AFN',
  ALL = 'ALL',
  DZD = 'DZD',
  AOA = 'AOA',
  ARS = 'ARS',
  AMD = 'AMD',
  AWG = 'AWG',
  AUD = 'AUD',
  BBD = 'BBD',
  AZN = 'AZN',
  BDT = 'BDT',
  BSD = 'BSD',
  BHD = 'BHD',
  BIF = 'BIF',
  BYN = 'BYN',
  BZD = 'BZD',
  BMD = 'BMD',
  BTN = 'BTN',
  BAM = 'BAM',
  BRL = 'BRL',
  BOB = 'BOB',
  BWP = 'BWP',
  BND = 'BND',
  BGN = 'BGN',
  MMK = 'MMK',
  KHR = 'KHR',
  CVE = 'CVE',
  KYD = 'KYD',
  XAF = 'XAF',
  CLP = 'CLP',
  CNY = 'CNY',
  COP = 'COP',
  KMF = 'KMF',
  CDF = 'CDF',
  CRC = 'CRC',
  HRK = 'HRK',
  CZK = 'CZK',
  DKK = 'DKK',
  DJF = 'DJF',
  DOP = 'DOP',
  XCD = 'XCD',
  EGP = 'EGP',
  ETB = 'ETB',
  FKP = 'FKP',
  XPF = 'XPF',
  FJD = 'FJD',
  GIP = 'GIP',
  GMD = 'GMD',
  GHS = 'GHS',
  GTQ = 'GTQ',
  GYD = 'GYD',
  GEL = 'GEL',
  GNF = 'GNF',
  HTG = 'HTG',
  HNL = 'HNL',
  HKD = 'HKD',
  HUF = 'HUF',
  ISK = 'ISK',
  INR = 'INR',
  IDR = 'IDR',
  ILS = 'ILS',
  IRR = 'IRR',
  IQD = 'IQD',
  JMD = 'JMD',
  JPY = 'JPY',
  JEP = 'JEP',
  JOD = 'JOD',
  KZT = 'KZT',
  KES = 'KES',
  KWD = 'KWD',
  KGS = 'KGS',
  LAK = 'LAK',
  LVL = 'LVL',
  LBP = 'LBP',
  LSL = 'LSL',
  LRD = 'LRD',
  LYD = 'LYD',
  LTL = 'LTL',
  MGA = 'MGA',
  MKD = 'MKD',
  MOP = 'MOP',
  MWK = 'MWK',
  MVR = 'MVR',
  MXN = 'MXN',
  MYR = 'MYR',
  MUR = 'MUR',
  MDL = 'MDL',
  MAD = 'MAD',
  MNT = 'MNT',
  MZN = 'MZN',
  NAD = 'NAD',
  NPR = 'NPR',
  ANG = 'ANG',
  NZD = 'NZD',
  NIO = 'NIO',
  NGN = 'NGN',
  NOK = 'NOK',
  OMR = 'OMR',
  PAB = 'PAB',
  PKR = 'PKR',
  PGK = 'PGK',
  PYG = 'PYG',
  PEN = 'PEN',
  PHP = 'PHP',
  PLN = 'PLN',
  QAR = 'QAR',
  RON = 'RON',
  RUB = 'RUB',
  RWF = 'RWF',
  WST = 'WST',
  SHP = 'SHP',
  SAR = 'SAR',
  STD = 'STD',
  RSD = 'RSD',
  SCR = 'SCR',
  SLL = 'SLL',
  SGD = 'SGD',
  SDG = 'SDG',
  SYP = 'SYP',
  ZAR = 'ZAR',
  KRW = 'KRW',
  SSP = 'SSP',
  SBD = 'SBD',
  LKR = 'LKR',
  SRD = 'SRD',
  SZL = 'SZL',
  SEK = 'SEK',
  CHF = 'CHF',
  TWD = 'TWD',
  THB = 'THB',
  TJS = 'TJS',
  TZS = 'TZS',
  TOP = 'TOP',
  TTD = 'TTD',
  TND = 'TND',
  TRY = 'TRY',
  TMT = 'TMT',
  UGX = 'UGX',
  UAH = 'UAH',
  AED = 'AED',
  UYU = 'UYU',
  UZS = 'UZS',
  VUV = 'VUV',
  VEF = 'VEF',
  VND = 'VND',
  XOF = 'XOF',
  YER = 'YER',
  ZMW = 'ZMW',
}

export enum SellingPlanInterval {
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  YEAR = 'YEAR',
}

export interface PricingPolicy {
  id: string;
  adjustmentType: SellingPlanPricingPolicyAdjustmentType;
  adjustmentValue: {
    percentage: number;
    amount: number;
    currencyCode: CurrencyCode;
  }
}

export interface Policy {
  id: string;
  interval: SellingPlanInterval;
  intervalCount: string;
}

export interface SellingPlan {
  id: string;
  name: string;
  billingPolicy: Policy;
  deliveryPolicy: Policy;
  pricingPolicies: PricingPolicy[];
}

export interface SellingPlanGroup {
  id: string;
  name: string;
  sellingPlans: SellingPlan[];
}
